package com.example.hopebridge.requests;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Builder
public class PlaceOrderRequest
{
    //private Long userId;
    private Long productId;

    private boolean usedVoucher;

    // Constructor, getters, and setters can be generated by Lombok
    // or manually implemented if not using Lombok
}
